version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    volumes:
      - app-db-mariadb/:/var/lib/database
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=app
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      # /opt/bitnami/mariadb/tmp/mysql.sock

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - app-db-mongodb/:/var/lib/database

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - app-db-redis/:/var/lib/database

  app:
    container_name: app
    image: bitnami/laravel:7
    tty: true
    environment:
      DB_HOST: mariadb
      DB_DATABASE: app
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows

volumes:
  app-db-mariadb:
  app-db-mongodb:
  app-db-redis: