version: '2'
services:
  mysql:
    container_name: mysql
    image: mariadb:latest
    # image: mysql:5.7
    ports:
      - "33061:3306"
    restart: unless-stopped
    volumes:
      - ./.docker-volumes-data/mysql:/var/lib/database
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  mongodb:
    container_name: mongodb
    image: mongodb:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
          - ./.docker-volumes-data/mongodb:/var/lib/database

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./.docker-volumes-data/redis:/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/application
    depends_on:
      - mysql
    entrypoint: php-fpm

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/application
    ports:
      - "8080:80"
    depends_on:
      - app
    environment:
      - NGINX_HOST=app.localhost
      - PHP_FPM_HOST=php-fpm