version: '2'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
  mysql:
    container_name: mysql
    # image: mysql:5.7
    image: mariadb:latest
    ports:
      - "33061:3306"
    volumes:
      - ./.docker-volumes-data/mysql:/var/lib/database
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-volumes-data/redis:/data
